import type { AppState, Category, CustomWorld, Student, ThemeKey, Lang } from "./app-types";

export const THEMES: { key: ThemeKey; emoji: string; label: string; color: string }[] = [
  { key: "space", emoji: "🚀", label: "Space", color: "sky" },
  { key: "farm", emoji: "🐮", label: "Farm", color: "leaf" },
  { key: "forest", emoji: "🦊", label: "Forest", color: "apricot" },
  { key: "sea", emoji: "🐬", label: "Sea", color: "sky" },
  { key: "superhero", emoji: "🦸", label: "Superhero", color: "coral" },
];

export const DEFAULT_CUSTOM_WORLDS: CustomWorld[] = [
  {
    id: "world-space",
    label: "Galactic Explorers",
    emoji: "🛸",
    color: "sky",
    frameStyle: "galaxy",
  },
  { id: "world-dino", label: "Dino Diggers", emoji: "🦕", color: "leaf", frameStyle: "dino" },
  { id: "world-ocean", label: "Deep Sea Divers", emoji: "🌊", color: "sky", frameStyle: "ocean" },
  { id: "world-safari", label: "Jungle Safari", emoji: "🦁", color: "honey", frameStyle: "safari" },
  { id: "world-stars", label: "Super Stars", emoji: "⭐", color: "coral", frameStyle: "stars" },
];

export const ACCESSORIES: { id: string; emoji: string; label: string }[] = [
  { id: "hat", emoji: "🎩", label: "Top hat" },
  { id: "cap", emoji: "🧢", label: "Cap" },
  { id: "crown", emoji: "👑", label: "Crown" },
  { id: "glasses", emoji: "🕶️", label: "Glasses" },
  { id: "bow", emoji: "🎀", label: "Bow" },
  { id: "star", emoji: "⭐", label: "Star" },
];

export const COLOR_FILTERS = ["honey", "coral", "leaf", "sky", "apricot"] as const;

export const DEFAULT_CATEGORIES: Category[] = [
  {
    id: "animals",
    enabled: true,
    smart: false,
    pool: "animals",
    usedOptionIds: [],
    labels: {
      en: "Animals",
      es: "Animales",
      pt: "Animais",
      zh: "动物",
      it: "Animali",
      fr: "Animaux",
      ja: "どうぶつ",
      ko: "동물",
      ru: "Животные",
      nl: "Dieren",
      de: "Tiere",
      el: "Ζώα",
      ar: "حيوانات",
    },
    question: {
      en: "What is your favorite animal?",
      es: "¿Cuál es tu animal favorito?",
      pt: "Qual é o seu animal favorito?",
      zh: "你最喜欢什么动物？",
      it: "Qual è il tuo animale preferito?",
      fr: "Quel est ton animal préféré ?",
      ja: "すきなどうぶつはどれ？",
      ko: "가장 좋아하는 동물은 무엇인가요?",
      ru: "Какое твое любимое животное?",
      nl: "Wat is jouw lievelingsdier?",
      de: "Was ist dein Lieblingstier?",
      el: "Ποιο είναι το αγαπημένο σου ζώο;",
      ar: "ما هو حيوانك المفضل؟",
    },
    options: [
      {
        id: "dino",
        emoji: "🦖",
        labels: {
          en: "Dinosaurs",
          es: "Dinosaurios",
          pt: "Dinossauros",
          zh: "恐龙",
          it: "Dinosauri",
          fr: "Dinosaures",
          ja: "きょうりゅう",
          ko: "공룡",
          ru: "Динозавры",
          nl: "Dinosaurussen",
          de: "Dinosaurier",
          el: "Δεινόσαυροι",
          ar: "ديناصورات",
        },
      },
      {
        id: "shark",
        emoji: "🦈",
        labels: {
          en: "Sharks",
          es: "Tiburones",
          pt: "Tubarões",
          zh: "鲨鱼",
          it: "Squali",
          fr: "Requins",
          ja: "サメ",
          ko: "상어",
          ru: "Акулы",
          nl: "Haaien",
          de: "Haie",
          el: "Καρχαρίες",
          ar: "أسماك القرش",
        },
      },
      {
        id: "bee",
        emoji: "🐝",
        labels: {
          en: "Bees",
          es: "Abejas",
          pt: "Abelhas",
          zh: "蜜蜂",
          it: "Api",
          fr: "Abeilles",
          ja: "ハチ",
          ko: "꿀벌",
          ru: "Пчелы",
          nl: "Bijen",
          de: "Bienen",
          el: "Μέλισσες",
          ar: "نحل",
        },
      },
      {
        id: "dolphin",
        emoji: "🐬",
        labels: {
          en: "Dolphins",
          es: "Delfines",
          pt: "Golfinhos",
          zh: "海豚",
          it: "Delfini",
          fr: "Dauphins",
          ja: "イルカ",
          ko: "돌고래",
          ru: "Дельфины",
          nl: "Dolfijnen",
          de: "Delfine",
          el: "Δελφίνια",
          ar: "دلافين",
        },
      },
      {
        id: "cat",
        emoji: "🐱",
        labels: {
          en: "Cats",
          es: "Gatos",
          pt: "Gatos",
          zh: "小猫",
          it: "Gatti",
          fr: "Chats",
          ja: "ネコ",
          ko: "고양이",
          ru: "Кошки",
          nl: "Katten",
          de: "Katzen",
          el: "Γάτες",
          ar: "قطط",
        },
      },
      {
        id: "frog",
        emoji: "🐸",
        labels: {
          en: "Frogs",
          es: "Ranas",
          pt: "Sapos",
          zh: "青蛙",
          it: "Rane",
          fr: "Grenouilles",
          ja: "カエル",
          ko: "개구리",
          ru: "Лягушки",
          nl: "Kikkers",
          de: "Frösche",
          el: "Βάτραχοι",
          ar: "ضفادع",
        },
      },
    ],
  },
  {
    id: "play",
    enabled: true,
    smart: false,
    pool: "play",
    usedOptionIds: [],
    labels: {
      en: "Play",
      es: "Juego",
      pt: "Brincadeiras",
      zh: "游戏活动",
      it: "Gioco",
      fr: "Jeux",
      ja: "あそび",
      ko: "놀이",
      ru: "Игры",
      nl: "Spelen",
      de: "Spielen",
      el: "Παιχνίδι",
      ar: "لعب",
    },
    question: {
      en: "What do you like to play?",
      es: "¿Qué te gusta jugar?",
      pt: "Do que você gosta de brincar?",
      zh: "你喜欢玩什么？",
      it: "A cosa ti piace giocare?",
      fr: "À quoi aimes-tu jouer ?",
      ja: "なにしてあそぶのがすき？",
      ko: "무엇을 하고 노는 것을 좋아하나요?",
      ru: "Во что ты любишь играть?",
      nl: "Wat speel je het liefst?",
      de: "Was spielst du am liebsten?",
      el: "Τι σου αρέσει να παίζεις;",
      ar: "بماذا تحب أن تلعب؟",
    },
    options: [
      {
        id: "blocks",
        emoji: "🧱",
        labels: {
          en: "Blocks",
          es: "Bloques",
          pt: "Blocos",
          zh: "积木",
          it: "Costruzioni",
          fr: "Blocs de construction",
          ja: "ブロック",
          ko: "블록",
          ru: "Кубики",
          nl: "Blokken",
          de: "Bausteine",
          el: "Τουβλάκια",
          ar: "مكعبات",
        },
      },
      {
        id: "paint",
        emoji: "🎨",
        labels: {
          en: "Painting",
          es: "Pintura",
          pt: "Pintura",
          zh: "画画",
          it: "Pittura",
          fr: "Peinture",
          ja: "おえかき",
          ko: "그림 그리기",
          ru: "Рисование",
          nl: "Schilderen",
          de: "Malen",
          el: "Ζωγραφική",
          ar: "الرسم",
        },
      },
      {
        id: "ball",
        emoji: "⚽",
        labels: {
          en: "Ball Games",
          es: "Pelota",
          pt: "Bola",
          zh: "球类运动",
          it: "Palla",
          fr: "Ballon",
          ja: "ボールあそび",
          ko: "공놀이",
          ru: "Игры с мячом",
          nl: "Balspellen",
          de: "Ballspiele",
          el: "Μπάλα",
          ar: "كرة",
        },
      },
      {
        id: "music",
        emoji: "🥁",
        labels: {
          en: "Music",
          es: "Música",
          pt: "Música",
          zh: "音乐",
          it: "Musica",
          fr: "Musique",
          ja: "おんがく",
          ko: "음악",
          ru: "Музыка",
          nl: "Muziek",
          de: "Musik",
          el: "Μουσική",
          ar: "موسيقى",
        },
      },
    ],
  },
  {
    id: "snacks",
    enabled: true,
    smart: false,
    pool: "food",
    usedOptionIds: [],
    labels: {
      en: "Snacks",
      es: "Meriendas",
      pt: "Lanches",
      zh: "点心加餐",
      it: "Merende",
      fr: "Goûters",
      ja: "おやつ",
      ko: "간식",
      ru: "Перекусы",
      nl: "Tussendoortjes",
      de: "Snacks",
      el: "Σνακ",
      ar: "وجبات خفيفة",
    },
    question: {
      en: "Which snack do you like more?",
      es: "¿Qué merienda te gusta más?",
      pt: "Qual lanche você prefere?",
      zh: "你更喜欢哪种点心？",
      it: "Quale merenda ti piace di più?",
      fr: "Quel goûter préfères-tu ?",
      ja: "どのおやつがすき？",
      ko: "어떤 간식을 더 좋아하나요?",
      ru: "Какой перекус ты любишь?",
      nl: "Welke snack vind je lekkerder?",
      de: "Welchen Snack magst du lieber?",
      el: "Ποιο σνακ σου αρέσει περισσότερο;",
      ar: "أي وجبة تحبها أكثر؟",
    },
    options: [
      {
        id: "apple",
        emoji: "🍎",
        labels: {
          en: "Apple",
          es: "Manzana",
          pt: "Maçã",
          zh: "苹果",
          it: "Mela",
          fr: "Pomme",
          ja: "りんご",
          ko: "사과",
          ru: "Яблоко",
          nl: "Appel",
          de: "Apfel",
          el: "Μήλο",
          ar: "تفاح",
        },
      },
      {
        id: "banana",
        emoji: "🍌",
        labels: {
          en: "Banana",
          es: "Plátano",
          pt: "Banana",
          zh: "香蕉",
          it: "Banana",
          fr: "Banane",
          ja: "バナナ",
          ko: "바나나",
          ru: "Банан",
          nl: "Banaan",
          de: "Banane",
          el: "Μπανάνα",
          ar: "موز",
        },
      },
      {
        id: "carrot",
        emoji: "🥕",
        labels: {
          en: "Carrots",
          es: "Zanahorias",
          pt: "Cenouras",
          zh: "胡萝卜",
          it: "Carote",
          fr: "Carottes",
          ja: "にんじん",
          ko: "당근",
          ru: "Морковь",
          nl: "Wortels",
          de: "Karotten",
          el: "Καρότα",
          ar: "جزر",
        },
      },
      {
        id: "cheese",
        emoji: "🧀",
        labels: {
          en: "Cheese",
          es: "Queso",
          pt: "Queijo",
          zh: "奶酪",
          it: "Formaggio",
          fr: "Fromage",
          ja: "チーズ",
          ko: "치즈",
          ru: "Сыр",
          nl: "Kaas",
          de: "Käse",
          el: "Τυρί",
          ar: "جبن",
        },
      },
    ],
  },
];

const student = (
  id: string,
  name: string,
  theme: ThemeKey,
  acc: string[],
  stars: number,
): Student => ({
  id,
  name,
  theme,
  accessories: acc,
  stars,
});

export const DEFAULT_STATE: AppState = {
  students: [
    student("ST-001", "Aurora", "space", ["cap"], 0),
    student("ST-002", "Robert", "farm", ["bow"], 0),
    student("ST-003", "Camari", "sea", ["glasses"], 0),
    student("ST-004", "Lucy", "forest", ["crown"], 0),
    student("ST-005", "Diego", "superhero", ["star"], 0),
  ],
  categories: DEFAULT_CATEGORIES,
  choices: [],
  pin: "1234",
  lang: "en",
  mode: "simple",
  lastSyncedAt: null,
  className: "Room 212",
  teacherName: "Mr. Bruno",
  grade: "PK",
  schoolName: "",
  uiTheme: "standard",
  customWorlds: DEFAULT_CUSTOM_WORLDS,
  showFeatureHints: true,
};
