import type { Lang } from "./app-types";

export interface Pic {
  id: string;
  emoji: string;
  labels: Record<Lang, string>;
  tags: string[];
}

interface RawPic {
  emoji: string;
  en: string;
  es: string;
  pt: string;
  zh: string;
  it: string;
  fr: string;
  ja: string;
  ko: string;
  ru: string;
  nl: string;
  de: string;
  el: string;
  ar: string;
  tags: string;
}

const RAW_ROWS: Record<string, RawPic[]> = {
  animals: [
    {
      emoji: "🦖",
      en: "Dinosaur",
      es: "Dinosaurio",
      pt: "Dinossauro",
      zh: "恐龙",
      it: "Dinosauro",
      fr: "Dinosaure",
      ja: "きょうりゅう",
      ko: "공룡",
      ru: "Динозавр",
      nl: "Dinosaurus",
      de: "Dinosaurier",
      el: "Δεινόσαυρος",
      ar: "ديناصور",
      tags: "dino rex big",
    },
    {
      emoji: "🦈",
      en: "Shark",
      es: "Tiburón",
      pt: "Tubarão",
      zh: "鲨鱼",
      it: "Squalo",
      fr: "Requin",
      ja: "サメ",
      ko: "상어",
      ru: "Акула",
      nl: "Haai",
      de: "Hai",
      el: "Καρχαρίας",
      ar: "قرش",
      tags: "sea fish ocean",
    },
    {
      emoji: "🐝",
      en: "Bee",
      es: "Abeja",
      pt: "Abelha",
      zh: "蜜蜂",
      it: "Ape",
      fr: "Abeille",
      ja: "ハチ",
      ko: "꿀벌",
      ru: "Пчела",
      nl: "Bij",
      de: "Biene",
      el: "Μέλισσα",
      ar: "نحلة",
      tags: "bug insect honey",
    },
    {
      emoji: "🐬",
      en: "Dolphin",
      es: "Delfín",
      pt: "Golfinho",
      zh: "海豚",
      it: "Delfino",
      fr: "Dauphin",
      ja: "イルカ",
      ko: "돌고래",
      ru: "Дельфин",
      nl: "Dolfijn",
      de: "Delfin",
      el: "Δελφίνι",
      ar: "دلفين",
      tags: "sea ocean swim",
    },
    {
      emoji: "🐱",
      en: "Cat",
      es: "Gato",
      pt: "Gato",
      zh: "小猫",
      it: "Gatto",
      fr: "Chat",
      ja: "ネコ",
      ko: "고양이",
      ru: "Кошка",
      nl: "Kat",
      de: "Katze",
      el: "Γάτα",
      ar: "قطة",
      tags: "pet kitten kitty",
    },
    {
      emoji: "🐶",
      en: "Dog",
      es: "Perro",
      pt: "Cachorro",
      zh: "小狗",
      it: "Cane",
      fr: "Chien",
      ja: "イヌ",
      ko: "강아지",
      ru: "Собака",
      nl: "Hond",
      de: "Hund",
      el: "Σκύλος",
      ar: "كلب",
      tags: "pet puppy",
    },
    {
      emoji: "🐸",
      en: "Frog",
      es: "Rana",
      pt: "Sapo",
      zh: "青蛙",
      it: "Rana",
      fr: "Grenouille",
      ja: "カエル",
      ko: "개구리",
      ru: "Лягушка",
      nl: "Kikker",
      de: "Frosch",
      el: "Βάτραχος",
      ar: "ضفدع",
      tags: "pond jump",
    },
    {
      emoji: "🦁",
      en: "Lion",
      es: "León",
      pt: "Leão",
      zh: "狮子",
      it: "Leone",
      fr: "Lion",
      ja: "ライオン",
      ko: "사자",
      ru: "Лев",
      nl: "Leeuw",
      de: "Löwe",
      el: "Λιοντάρι",
      ar: "أسد",
      tags: "zoo big cat",
    },
    {
      emoji: "🐘",
      en: "Elephant",
      es: "Elefante",
      pt: "Elefante",
      zh: "大象",
      it: "Elefante",
      fr: "Éléphant",
      ja: "ゾウ",
      ko: "코끼리",
      ru: "Слон",
      nl: "Olifant",
      de: "Elefant",
      el: "Ελέφαντας",
      ar: "فيل",
      tags: "zoo big",
    },
    {
      emoji: "🐧",
      en: "Penguin",
      es: "Pingüino",
      pt: "Pinguim",
      zh: "企鹅",
      it: "Pinguino",
      fr: "Manchot",
      ja: "ペンギン",
      ko: "펭귄",
      ru: "Пингвин",
      nl: "Pinguïn",
      de: "Pinguin",
      el: "Πιγκουίνος",
      ar: "بطريق",
      tags: "ice bird cold",
    },
    {
      emoji: "🦋",
      en: "Butterfly",
      es: "Mariposa",
      pt: "Borboleta",
      zh: "蝴蝶",
      it: "Farfalla",
      fr: "Papillon",
      ja: "チョウ",
      ko: "나비",
      ru: "Бабочка",
      nl: "Vlinder",
      de: "Schmetterling",
      el: "Πεταλούδα",
      ar: "فراشة",
      tags: "bug wings",
    },
    {
      emoji: "🐢",
      en: "Turtle",
      es: "Tortuga",
      pt: "Tartaruga",
      zh: "乌龟",
      it: "Tartaruga",
      fr: "Tortue",
      ja: "カメ",
      ko: "거북이",
      ru: "Черепаха",
      nl: "Schildpad",
      de: "Schildkröte",
      el: "Χελώνα",
      ar: "سلحفاة",
      tags: "slow shell pet",
    },
    {
      emoji: "🐴",
      en: "Horse",
      es: "Caballo",
      pt: "Cavalo",
      zh: "马",
      it: "Cavallo",
      fr: "Cheval",
      ja: "ウマ",
      ko: "말",
      ru: "Лошадь",
      nl: "Paard",
      de: "Pferd",
      el: "Άλογο",
      ar: "حصان",
      tags: "farm ride",
    },
    {
      emoji: "🐮",
      en: "Cow",
      es: "Vaca",
      pt: "Vaca",
      zh: "奶牛",
      it: "Mucca",
      fr: "Vache",
      ja: "ウシ",
      ko: "소",
      ru: "Корова",
      nl: "Koe",
      de: "Kuh",
      el: "Αγελάδα",
      ar: "بقرة",
      tags: "farm milk",
    },
    {
      emoji: "🐷",
      en: "Pig",
      es: "Cerdo",
      pt: "Porco",
      zh: "小猪",
      it: "Maiale",
      fr: "Cochon",
      ja: "ブタ",
      ko: "돼지",
      ru: "Свинья",
      nl: "Varken",
      de: "Schwein",
      el: "Γουρούνι",
      ar: "خنزير",
      tags: "farm",
    },
    {
      emoji: "🐑",
      en: "Sheep",
      es: "Oveja",
      pt: "Ovelha",
      zh: "绵羊",
      it: "Pecora",
      fr: "Mouton",
      ja: "ヒツジ",
      ko: "양",
      ru: "Овечка",
      nl: "Schaap",
      de: "Schaf",
      el: "Πρόβατο",
      ar: "خروف",
      tags: "farm wool",
    },
    {
      emoji: "🐔",
      en: "Chicken",
      es: "Gallina",
      pt: "Galinha",
      zh: "母鸡",
      it: "Gallina",
      fr: "Poule",
      ja: "ニワトリ",
      ko: "닭",
      ru: "Курица",
      nl: "Kip",
      de: "Huhn",
      el: "Κότα",
      ar: "دجاجة",
      tags: "farm bird",
    },
    {
      emoji: "🦉",
      en: "Owl",
      es: "Búho",
      pt: "Coruja",
      zh: "猫头鹰",
      it: "Gufo",
      fr: "Hibou",
      ja: "フクロウ",
      ko: "부엉이",
      ru: "Сова",
      nl: "Uil",
      de: "Eule",
      el: "Κουκουβάγια",
      ar: "بومة",
      tags: "bird night",
    },
    {
      emoji: "🐙",
      en: "Octopus",
      es: "Pulpo",
      pt: "Polvo",
      zh: "章鱼",
      it: "Polpo",
      fr: "Pieuvre",
      ja: "タコ",
      ko: "문어",
      ru: "Осьминог",
      nl: "Inktvis",
      de: "Oktopus",
      el: "Χταπόδι",
      ar: "أخطبوط",
      tags: "sea ocean",
    },
    {
      emoji: "🐳",
      en: "Whale",
      es: "Ballena",
      pt: "Baleia",
      zh: "鲸鱼",
      it: "Balena",
      fr: "Baleine",
      ja: "クジラ",
      ko: "고래",
      ru: "Кит",
      nl: "Walvis",
      de: "Wal",
      el: "Фάλαινα",
      ar: "حوت",
      tags: "sea ocean big",
    },
    {
      emoji: "🦒",
      en: "Giraffe",
      es: "Jirafa",
      pt: "Girafa",
      zh: "长颈鹿",
      it: "Giraffa",
      fr: "Girafe",
      ja: "キリン",
      ko: "기린",
      ru: "Жираф",
      nl: "Giraffe",
      de: "Giraffe",
      el: "Καμηλοπάρδαλη",
      ar: "زرافة",
      tags: "zoo tall",
    },
    {
      emoji: "🐒",
      en: "Monkey",
      es: "Mono",
      pt: "Macaco",
      zh: "猴子",
      it: "Scimmia",
      fr: "Singe",
      ja: "サル",
      ko: "원숭이",
      ru: "Обезьяна",
      nl: "Aap",
      de: "Affe",
      el: "Μαϊμού",
      ar: "قرد",
      tags: "zoo jungle",
    },
    {
      emoji: "🐰",
      en: "Rabbit",
      es: "Conejo",
      pt: "Coelho",
      zh: "兔子",
      it: "Coniglio",
      fr: "Lapin",
      ja: "ウサギ",
      ko: "토끼",
      ru: "Кролик",
      nl: "Konijn",
      de: "Hase",
      el: "Κουνέλι",
      ar: "أرنب",
      tags: "pet bunny hop",
    },
    {
      emoji: "🦜",
      en: "Parrot",
      es: "Loro",
      pt: "Papagaio",
      zh: "鹦鹉",
      it: "Pappagallo",
      fr: "Perroquet",
      ja: "オウム",
      ko: "앵무새",
      ru: "Попугай",
      nl: "Papegaai",
      de: "Papagei",
      el: "Παπαγάλος",
      ar: "ببغاء",
      tags: "pet bird talk",
    },
    {
      emoji: "🐹",
      en: "Hamster",
      es: "Hámster",
      pt: "Hamster",
      zh: "仓鼠",
      it: "Criceto",
      fr: "Hamster",
      ja: "ハムスター",
      ko: "햄스터",
      ru: "Хомяк",
      nl: "Hamster",
      de: "Hamster",
      el: "Χάμστερ",
      ar: "هامستر",
      tags: "pet small",
    },
    {
      emoji: "🐠",
      en: "Goldfish",
      es: "Pez dorado",
      pt: "Peixinho",
      zh: "金鱼",
      it: "Pesce rosso",
      fr: "Poisson rouge",
      ja: "金魚",
      ko: "금붕어",
      ru: "Золотая рыбка",
      nl: "Goudvis",
      de: "Goldfisch",
      el: "Χρυσόψαρο",
      ar: "سمكة ذهبية",
      tags: "pet fish tank",
    },
    {
      emoji: "🦎",
      en: "Lizard",
      es: "Lagarto",
      pt: "Lagarto",
      zh: "蜥蜴",
      it: "Lucertola",
      fr: "Lézard",
      ja: "トカゲ",
      ko: "도마뱀",
      ru: "Ящерица",
      nl: "Hagedis",
      de: "Eidechse",
      el: "Σαṙτάκι",
      ar: "سحلية",
      tags: "pet reptile",
    },
    {
      emoji: "🐞",
      en: "Ladybug",
      es: "Mariquita",
      pt: "Joaninha",
      zh: "瓢虫",
      it: "Coccinella",
      fr: "Coccinelle",
      ja: "テントウムシ",
      ko: "무당벌레",
      ru: "Божья коровка",
      nl: "Lieveheersbeestje",
      de: "Marienkäfer",
      el: "Πασχαλίτσα",
      ar: "دعسوقة",
      tags: "bug red",
    },
  ],
  food: [
    {
      emoji: "🍎",
      en: "Apple",
      es: "Manzana",
      pt: "Maçã",
      zh: "苹果",
      it: "Mela",
      fr: "Pomme",
      ja: "リンゴ",
      ko: "사과",
      ru: "Яблоко",
      nl: "Appel",
      de: "Apfel",
      el: "Μήλο",
      ar: "تفاح",
      tags: "fruit snack red",
    },
    {
      emoji: "🍌",
      en: "Banana",
      es: "Plátano",
      pt: "Banana",
      zh: "香蕉",
      it: "Banana",
      fr: "Banane",
      ja: "バナナ",
      ko: "바나나",
      ru: "Банан",
      nl: "Banaan",
      de: "Banane",
      el: "Μπανάνα",
      ar: "موز",
      tags: "fruit snack",
    },
    {
      emoji: "🥕",
      en: "Carrot",
      es: "Zanahoria",
      pt: "Cenoura",
      zh: "胡萝卜",
      it: "Carota",
      fr: "Carotte",
      ja: "ニンジン",
      ko: "당근",
      ru: "Морковь",
      nl: "Wortel",
      de: "Karotte",
      el: "Καρότο",
      ar: "جزر",
      tags: "veggie snack",
    },
    {
      emoji: "🧀",
      en: "Cheese",
      es: "Queso",
      pt: "Queijo",
      zh: "奶酪",
      it: "Formaggio",
      fr: "Fromage",
      ja: "チーズ",
      ko: "치즈",
      ru: "Сыр",
      nl: "Kaas",
      de: "Käse",
      el: "Τυρί",
      ar: "جبن",
      tags: "snack dairy",
    },
    {
      emoji: "🍓",
      en: "Strawberry",
      es: "Fresa",
      pt: "Morango",
      zh: "草莓",
      it: "Fragola",
      fr: "Fraise",
      ja: "イチゴ",
      ko: "딸기",
      ru: "Клубника",
      nl: "Aardbei",
      de: "Erdbeere",
      el: "Φράουλα",
      ar: "فراولة",
      tags: "fruit berry",
    },
    {
      emoji: "🍇",
      en: "Grapes",
      es: "Uvas",
      pt: "Uvas",
      zh: "葡萄",
      it: "Uva",
      fr: "Raisin",
      ja: "ブドウ",
      ko: "포도",
      ru: "Виноград",
      nl: "Druiven",
      de: "Trauben",
      el: "Σταφύλια",
      ar: "عنب",
      tags: "fruit",
    },
    {
      emoji: "🍉",
      en: "Watermelon",
      es: "Sandía",
      pt: "Melancia",
      zh: "西瓜",
      it: "Anguria",
      fr: "Pastèque",
      ja: "スイカ",
      ko: "수박",
      ru: "Арбуз",
      nl: "Watermeloen",
      de: "Wassermelone",
      el: "Καρπούζι",
      ar: "بطيخ",
      tags: "fruit summer",
    },
    {
      emoji: "🥦",
      en: "Broccoli",
      es: "Brócoli",
      pt: "Brócolis",
      zh: "西兰花",
      it: "Broccoli",
      fr: "Brocoli",
      ja: "ブロッコリー",
      ko: "브로콜리",
      ru: "Брокколи",
      nl: "Broccoli",
      de: "Brokkoli",
      el: "Μπρόκολο",
      ar: "بروكلي",
      tags: "veggie green",
    },
    {
      emoji: "🍕",
      en: "Pizza",
      es: "Pizza",
      pt: "Pizza",
      zh: "披萨",
      it: "Pizza",
      fr: "Pizza",
      ja: "ピザ",
      ko: "피자",
      ru: "Пицца",
      nl: "Pizza",
      de: "Pizza",
      el: "Πίτσα",
      ar: "بيتزا",
      tags: "dinner",
    },
    {
      emoji: "🥪",
      en: "Sandwich",
      es: "Sándwich",
      pt: "Sanduíche",
      zh: "三明治",
      it: "Panino",
      fr: "Sandwich",
      ja: "サンドイッチ",
      ko: "샌드위치",
      ru: "Бутерброд",
      nl: "Sandwich",
      de: "Sandwich",
      el: "Σάντουιτς",
      ar: "شطيرة",
      tags: "lunch",
    },
    {
      emoji: "🍪",
      en: "Cookie",
      es: "Galleta",
      pt: "Biscoito",
      zh: "饼干",
      it: "Biscotto",
      fr: "Biscuit",
      ja: "クッキー",
      ko: "쿠키",
      ru: "Печенье",
      nl: "Koekje",
      de: "Keks",
      el: "Μπισκότο",
      ar: "بسكويت",
      tags: "treat sweet",
    },
    {
      emoji: "🥨",
      en: "Pretzel",
      es: "Pretzel",
      pt: "Pretzel",
      zh: " pretzel",
      it: "Pretzel",
      fr: "Pretzel",
      ja: "プレッツェル",
      ko: "프레첼",
      ru: "Крендель",
      nl: "Pretzel",
      de: "Brezel",
      el: "Πρέτσελ",
      ar: "بريتزل",
      tags: "snack salty",
    },
    {
      emoji: "🍿",
      en: "Popcorn",
      es: "Palomitas",
      pt: "Pipoca",
      zh: "爆米花",
      it: "Popcorn",
      fr: "Popcorn",
      ja: "ポップコーン",
      ko: "팝콘",
      ru: "Попкорн",
      nl: "Popcorn",
      de: "Popcorn",
      el: "Ποπ κορν",
      ar: "فشار",
      tags: "snack movie",
    },
    {
      emoji: "🥛",
      en: "Milk",
      es: "Leche",
      pt: "Leite",
      zh: "牛奶",
      it: "Latte",
      fr: "Lait",
      ja: "牛乳",
      ko: "우유",
      ru: "Молоко",
      nl: "Melk",
      de: "Milch",
      el: "Γάλα",
      ar: "حليب",
      tags: "drink",
    },
    {
      emoji: "🍊",
      en: "Orange",
      es: "Naranja",
      pt: "Laranja",
      zh: "橙子",
      it: "Arancia",
      fr: "Orange",
      ja: "オレンジ",
      ko: "오렌지",
      ru: "Апельсин",
      nl: "Sinaasappel",
      de: "Orange",
      el: "Πορτοκάλι",
      ar: "برتقال",
      tags: "fruit",
    },
    {
      emoji: "🥑",
      en: "Avocado",
      es: "Aguacate",
      pt: "Abacate",
      zh: "牛油果",
      it: "Avocado",
      fr: "Avocat",
      ja: "アボカド",
      ko: "아보카도",
      ru: "Авокадо",
      nl: "Avocado",
      de: "Avocado",
      el: "Αβοκάντο",
      ar: "أفوكادو",
      tags: "veggie green",
    },
  ],
  play: [
    {
      emoji: "🧱",
      en: "Blocks",
      es: "Bloques",
      pt: "Blocos",
      zh: "积木",
      it: "Costruzioni",
      fr: "Blocs",
      ja: "ブロック",
      ko: "블록",
      ru: "Кубики",
      nl: "Blokken",
      de: "Bausteine",
      el: "Τουβλάκια",
      ar: "مكعبات",
      tags: "build toys",
    },
    {
      emoji: "🎨",
      en: "Painting",
      es: "Pintura",
      pt: "Pintura",
      zh: "画画",
      it: "Pittura",
      fr: "Peinture",
      ja: "おえかき",
      ko: "그림그리기",
      ru: "Рисование",
      nl: "Schilderen",
      de: "Malen",
      el: "Ζωγραφική",
      ar: "رسم",
      tags: "art craft",
    },
    {
      emoji: "⚽",
      en: "Ball",
      es: "Pelota",
      pt: "Bola",
      zh: "球",
      it: "Pallone",
      fr: "Ballon",
      ja: "ボール",
      ko: "공",
      ru: "Мяч",
      nl: "Bal",
      de: "Ball",
      el: "Μπάλα",
      ar: "كرة",
      tags: "sport outside",
    },
    {
      emoji: "🥁",
      en: "Music",
      es: "Música",
      pt: "Música",
      zh: "音乐",
      it: "Musica",
      fr: "Musique",
      ja: "音楽",
      ko: "음악",
      ru: "Музыка",
      nl: "Muziek",
      de: "Musik",
      el: "Μουσική",
      ar: "موسيقى",
      tags: "drum sound",
    },
    {
      emoji: "🧸",
      en: "Teddy bear",
      es: "Osito",
      pt: "Ursinho",
      zh: "泰迪熊",
      it: "Orsacchiotto",
      fr: "Ours en peluche",
      ja: "テディベア",
      ko: "곰인형",
      ru: "Мишка",
      nl: "Teddybeer",
      de: "Teddybär",
      el: "Αρκουδάκι",
      ar: "دبدوب",
      tags: "toys cuddle",
    },
    {
      emoji: "🚂",
      en: "Train set",
      es: "Tren",
      pt: "Trem",
      zh: "火车",
      it: "Treno",
      fr: "Train",
      ja: "電車",
      ko: "기차",
      ru: "Поезд",
      nl: "Trein",
      de: "Eisenbahn",
      el: "Τρένο",
      ar: "قطار",
      tags: "toys vehicle",
    },
    {
      emoji: "🧩",
      en: "Puzzle",
      es: "Rompecabezas",
      pt: "Quebra-cabeça",
      zh: "拼图",
      it: "Puzzle",
      fr: "Puzzle",
      ja: "パズル",
      ko: "퍼즐",
      ru: "Пазл",
      nl: "Puzzel",
      de: "Puzzle",
      el: "Παζλ",
      ar: "أحجية",
      tags: "quiet game",
    },
    {
      emoji: "📚",
      en: "Books",
      es: "Libros",
      pt: "Livros",
      zh: "书籍",
      it: "Libri",
      fr: "Livres",
      ja: "本",
      ko: "책",
      ru: "Книги",
      nl: "Boeken",
      de: "Bücher",
      el: "Βιβλία",
      ar: "كتب",
      tags: "quiet read",
    },
    {
      emoji: "🪁",
      en: "Kite",
      es: "Cometa",
      pt: "Pipa",
      zh: "风筝",
      it: "Aquilone",
      fr: "Cerf-volant",
      ja: "凧",
      ko: "연",
      ru: "Воздушный змей",
      nl: "Vlieger",
      de: "Drachen",
      el: "Χαρταετός",
      ar: "طائرة ورقية",
      tags: "outside wind",
    },
    {
      emoji: "🩰",
      en: "Dancing",
      es: "Bailar",
      pt: "Dança",
      zh: "跳舞",
      it: "Danza",
      fr: "Danse",
      ja: "ダンス",
      ko: "춤추기",
      ru: "Танцы",
      nl: "Dansen",
      de: "Tanzen",
      el: "Χορός",
      ar: "رقص",
      tags: "move music",
    },
    {
      emoji: "🛝",
      en: "Slide",
      es: "Tobogán",
      pt: "Escorregador",
      zh: "滑梯",
      it: "Scivolo",
      fr: "Toboggan",
      ja: "滑り台",
      ko: "미끄럼틀",
      ru: "Горка",
      nl: "Glijbaan",
      de: "Rutsche",
      el: "Τσουλήθρα",
      ar: "زحليقة",
      tags: "playground outside",
    },
    {
      emoji: "🏊",
      en: "Swimming",
      es: "Nadar",
      pt: "Natação",
      zh: "游泳",
      it: "Nuoto",
      fr: "Natation",
      ja: "水泳",
      ko: "수영",
      ru: "Плавание",
      nl: "Zwemmen",
      de: "Schwimmen",
      el: "Κολύμβηση",
      ar: "سباحة",
      tags: "water sport",
    },
    {
      emoji: "🚲",
      en: "Bike",
      es: "Bicicleta",
      pt: "Bicicleta",
      zh: "自行车",
      it: "Bicicletta",
      fr: "Vélo",
      ja: "自転車",
      ko: "자전거",
      ru: "Велосипед",
      nl: "Fiets",
      de: "Fahrrad",
      el: "Ποδήλατο",
      ar: "دراجة",
      tags: "outside ride",
    },
    {
      emoji: "🧼",
      en: "Bubbles",
      es: "Burbujas",
      pt: "Bolhas de sabão",
      zh: "泡泡",
      it: "Bolle di sapone",
      fr: "Bulles de savon",
      ja: "シャボン玉",
      ko: "비누방울",
      ru: "Мыльные пузыри",
      nl: "Bellenblaas",
      de: "Seifenblasen",
      el: "Φουσκάλες",
      ar: "فقاعات",
      tags: "outside water",
    },
  ],
  colors: [
    {
      emoji: "🔴",
      en: "Red",
      es: "Rojo",
      pt: "Vermelho",
      zh: "红色",
      it: "Rosso",
      fr: "Rouge",
      ja: "赤",
      ko: "빨간색",
      ru: "Красный",
      nl: "Rood",
      de: "Rot",
      el: "Κόκκινο",
      ar: "أحمر",
      tags: "color",
    },
    {
      emoji: "🔵",
      en: "Blue",
      es: "Azul",
      pt: "Azul",
      zh: "蓝色",
      it: "Blu",
      fr: "Bleu",
      ja: "青",
      ko: "파란색",
      ru: "Синий",
      nl: "Blauw",
      de: "Blau",
      el: "Μπλε",
      ar: "أزرق",
      tags: "color",
    },
    {
      emoji: "🟡",
      en: "Yellow",
      es: "Amarillo",
      pt: "Amarelo",
      zh: "黄色",
      it: "Giallo",
      fr: "Jaune",
      ja: "黄色",
      ko: "노란색",
      ru: "Желтый",
      nl: "Geel",
      de: "Gelb",
      el: "Κίτρινο",
      ar: "أصفر",
      tags: "color",
    },
    {
      emoji: "🟢",
      en: "Green",
      es: "Verde",
      pt: "Verde",
      zh: "绿色",
      it: "Verde",
      fr: "Vert",
      ja: "緑",
      ko: "초록색",
      ru: "Зеленый",
      nl: "Groen",
      de: "Grün",
      el: "Πράσινο",
      ar: "أخضر",
      tags: "color",
    },
    {
      emoji: "🟣",
      en: "Purple",
      es: "Morado",
      pt: "Roxo",
      zh: "紫色",
      it: "Viola",
      fr: "Violet",
      ja: "紫",
      ko: "보라색",
      ru: "Фиолетовый",
      nl: "Paars",
      de: "Lila",
      el: "Μωβ",
      ar: "بنفسجي",
      tags: "color",
    },
    {
      emoji: "🟠",
      en: "Orange",
      es: "Naranja",
      pt: "Laranja",
      zh: "橙色",
      it: "Arancione",
      fr: "Orange",
      ja: "オレンジ",
      ko: "주황색",
      ru: "Оранжевый",
      nl: "Oranje",
      de: "Orange",
      el: "Πορτοκαλί",
      ar: "برتقالي",
      tags: "color",
    },
    {
      emoji: "🩷",
      en: "Pink",
      es: "Rosa",
      pt: "Rosa",
      zh: "粉红色",
      it: "Rosa",
      fr: "Rose",
      ja: "ピンク",
      ko: "분홍색",
      ru: "Розовый",
      nl: "Roze",
      de: "Rosa",
      el: "Розовый",
      ar: "وردي",
      tags: "color",
    },
    {
      emoji: "⚫",
      en: "Black",
      es: "Negro",
      pt: "Preto",
      zh: "黑色",
      it: "Nero",
      fr: "Noir",
      ja: "黒",
      ko: "검은색",
      ru: "Черный",
      nl: "Zwart",
      de: "Schwarz",
      el: "Мавро",
      ar: "أسود",
      tags: "color",
    },
  ],
  weather: [
    {
      emoji: "☀️",
      en: "Sunny",
      es: "Soleado",
      pt: "Ensolarado",
      zh: "晴天",
      it: "Soleggiato",
      fr: "Ensoleillé",
      ja: "晴れ",
      ko: "맑음",
      ru: "Солнечно",
      nl: "Zonnig",
      de: "Sonnig",
      el: "Ηλιοφάνεια",
      ar: "مشمس",
      tags: "weather sky",
    },
    {
      emoji: "🌧️",
      en: "Rainy",
      es: "Lluvioso",
      pt: "Chuvoso",
      zh: "下雨",
      it: "Piovoso",
      fr: "Pluvieux",
      ja: "雨",
      ko: "비",
      ru: "Дождливо",
      nl: "Regenachtig",
      de: "Regnerisch",
      el: "Βροχερός",
      ar: "ممطر",
      tags: "weather water",
    },
    {
      emoji: "❄️",
      en: "Snowy",
      es: "Nevado",
      pt: "Nevando",
      zh: "下雪",
      it: "Nevoso",
      fr: "Neigeux",
      ja: "雪",
      ko: "눈",
      ru: "Снежно",
      nl: "Sneeuw",
      de: "Schneereich",
      el: "Χιονιάς",
      ar: "ثلجي",
      tags: "weather cold",
    },
    {
      emoji: "🌈",
      en: "Rainbow",
      es: "Arcoíris",
      pt: "Arco-íris",
      zh: "彩虹",
      it: "Arcobaleno",
      fr: "Arc-en-ciel",
      ja: "虹",
      ko: "무지개",
      ru: "Радуга",
      nl: "Regenboog",
      de: "Regenbogen",
      el: "Ουράνιο τόξο",
      ar: "قوس قزح",
      tags: "weather color",
    },
    {
      emoji: "⛈️",
      en: "Stormy",
      es: "Tormenta",
      pt: "Tempestade",
      zh: "暴风雨",
      it: "Temporale",
      fr: "Orageux",
      ja: "嵐",
      ko: "폭풍우",
      ru: "Шторм",
      nl: "Stormachtig",
      de: "Stürmisch",
      el: "Καταιγίδα",
      ar: "عاصفة",
      tags: "weather loud",
    },
    {
      emoji: "🍃",
      en: "Windy",
      es: "Ventoso",
      pt: "Ventoso",
      zh: "有风",
      it: "Ventoso",
      fr: "Venteux",
      ja: "風",
      ko: "바람",
      ru: "Ветрено",
      nl: "Winderig",
      de: "Windig",
      el: "Ανεμώδης",
      ar: "عاصف",
      tags: "weather air",
    },
  ],
  vehicles: [
    {
      emoji: "🚒",
      en: "Fire truck",
      es: "Camión de bomberos",
      pt: "Carro de bombeiro",
      zh: "消防车",
      it: "Autopompa",
      fr: "Camion de pompier",
      ja: "消防車",
      ko: "소방차",
      ru: "Пожарная машина",
      nl: "Brandweerauto",
      de: "Feuerwehrauto",
      el: "Πυροσβεστικό",
      ar: "شاحنة إطفاء",
      tags: "vehicle rescue",
    },
    {
      emoji: "🚀",
      en: "Rocket",
      es: "Cohete",
      pt: "Foguete",
      zh: "火箭",
      it: "Razzo",
      fr: "Fusée",
      ja: "ロケット",
      ko: "로켓",
      ru: "Ракета",
      nl: "Raket",
      de: "Rakete",
      el: "Πυραυλος",
      ar: "صاروخ",
      tags: "space vehicle",
    },
    {
      emoji: "🚜",
      en: "Tractor",
      es: "Tractor",
      pt: "Trator",
      zh: "拖拉机",
      it: "Trattore",
      fr: "Tracteur",
      ja: "トラクター",
      ko: "트랙터",
      ru: "Трактор",
      nl: "Tractor",
      de: "Traktor",
      el: "Τρακτέρ",
      ar: "جرار",
      tags: "farm vehicle",
    },
    {
      emoji: "🚌",
      en: "Bus",
      es: "Autobús",
      pt: "Ônibus",
      zh: "公交车",
      it: "Autobus",
      fr: "Bus",
      ja: "バス",
      ko: "버스",
      ru: "Автобус",
      nl: "Bus",
      de: "Bus",
      el: "Λεωφορείο",
      ar: "حافلة",
      tags: "vehicle school",
    },
    {
      emoji: "✈️",
      en: "Airplane",
      es: "Avión",
      pt: "Avião",
      zh: "飞机",
      it: "Aereo",
      fr: "Avion",
      ja: "飛行機",
      ko: "비행기",
      ru: "Самолет",
      nl: "Vliegtuig",
      de: "Flugzeug",
      el: "Αεροπλάνο",
      ar: "طائرة",
      tags: "vehicle fly",
    },
    {
      emoji: "🚁",
      en: "Helicopter",
      es: "Helicóptero",
      pt: "Helicóptero",
      zh: "直升机",
      it: "Eliottero",
      fr: "Hélicoptère",
      ja: "ヘリコプター",
      ko: "헬리콥터",
      ru: "Вертолет",
      nl: "Helikopter",
      de: "Hubschrauber",
      el: "Ελικόπτερο",
      ar: "مروحية",
      tags: "vehicle fly",
    },
    {
      emoji: "🛶",
      en: "Canoe",
      es: "Canoa",
      pt: "Canoa",
      zh: "独木舟",
      it: "Canoa",
      fr: "Canoë",
      ja: "カヌー",
      ko: "카누",
      ru: "Каноэ",
      nl: "Kano",
      de: "Kanu",
      el: "Κανό",
      ar: "قارب",
      tags: "water vehicle",
    },
    {
      emoji: "🚓",
      en: "Police car",
      es: "Patrulla",
      pt: "Viatura policial",
      zh: "警车",
      it: "Auto della polizia",
      fr: "Voiture de police",
      ja: "パトカー",
      ko: "경찰차",
      ru: "Полицейская машина",
      nl: "Politieauto",
      de: "Polizeiauto",
      el: "Περιπολικό",
      ar: "سيارة شرطة",
      tags: "vehicle rescue",
    },
  ],
  feelings: [
    {
      emoji: "😀",
      en: "Happy",
      es: "Feliz",
      pt: "Feliz",
      zh: "开心",
      it: "Felice",
      fr: "Heureux",
      ja: "うれしい",
      ko: "행복함",
      ru: "Счастливый",
      nl: "Blij",
      de: "Glücklich",
      el: "Χαρούμενος",
      ar: "سعيد",
      tags: "feeling",
    },
    {
      emoji: "😢",
      en: "Sad",
      es: "Triste",
      pt: "Triste",
      zh: "伤心",
      it: "Triste",
      fr: "Triste",
      ja: "かなしい",
      ko: "슬픔",
      ru: "Грустный",
      nl: "Verdrietig",
      de: "Traurig",
      el: "Λυπημένος",
      ar: "حزين",
      tags: "feeling",
    },
    {
      emoji: "😴",
      en: "Sleepy",
      es: "Con sueño",
      pt: "Com sono",
      zh: "困倦",
      it: "Sonnolento",
      fr: "Fatigué",
      ja: "眠い",
      ko: "졸림",
      ru: "Сонный",
      nl: "Slaperig",
      de: "Müde",
      el: "Νυσταγμένος",
      ar: "نعسان",
      tags: "feeling",
    },
    {
      emoji: "😲",
      en: "Surprised",
      es: "Sorprendido",
      pt: "Surpreso",
      zh: "惊讶",
      it: "Sorpreso",
      fr: "Surpris",
      ja: "びっくり",
      ko: "놀람",
      ru: "Удивленный",
      nl: "Verrast",
      de: "Überrascht",
      el: "Εκπληκτικός",
      ar: "متفاجئ",
      tags: "feeling",
    },
    {
      emoji: "😡",
      en: "Angry",
      es: "Enojado",
      pt: "Bravo",
      zh: "生气",
      it: "Arrabbiato",
      fr: "En colère",
      ja: "怒っている",
      ko: "화남",
      ru: "Злой",
      nl: "Boos",
      de: "Wütend",
      el: "Θυμωμένος",
      ar: "غاضب",
      tags: "feeling",
    },
    {
      emoji: "🤗",
      en: "Cozy",
      es: "Acogedor",
      pt: "Aconchegante",
      zh: "舒适",
      it: "Accogliente",
      fr: "Confortable",
      ja: "心地よい",
      ko: "아늑함",
      ru: "Уютный",
      nl: "Gezellig",
      de: "Gemütlich",
      el: "Άνετος",
      ar: "مرتاح",
      tags: "feeling calm",
    },
  ],
  nature: [
    {
      emoji: "🌻",
      en: "Sunflower",
      es: "Girasol",
      pt: "Girassol",
      zh: "向日葵",
      it: "Girasole",
      fr: "Tournesol",
      ja: "ヒマワリ",
      ko: "해바라기",
      ru: "Подсолнух",
      nl: "Zonnebloem",
      de: "Sonnenblume",
      el: "Ηλιοτρόπιο",
      ar: "عباد الشمس",
      tags: "flower plant",
    },
    {
      emoji: "🌳",
      en: "Tree",
      es: "Árbol",
      pt: "Árvore",
      zh: "树",
      it: "Albero",
      fr: "Arbre",
      ja: "木",
      ko: "나무",
      ru: "Дерево",
      nl: "Boom",
      de: "Baum",
      el: "Δέντρο",
      ar: "شجرة",
      tags: "forest plant",
    },
    {
      emoji: "🐚",
      en: "Seashell",
      es: "Concha",
      pt: "Concha",
      zh: "贝壳",
      it: "Conchiglia",
      fr: "Coquillage",
      ja: "貝殻",
      ko: "조개껍질",
      ru: "Ракушка",
      nl: "Schelp",
      de: "Muschel",
      el: "Κοχύλι",
      ar: "صدفة",
      tags: "beach sea",
    },
    {
      emoji: "🪨",
      en: "Rock",
      es: "Roca",
      pt: "Rocha",
      zh: "石头",
      it: "Roccia",
      fr: "Rocher",
      ja: "岩",
      ko: "바위",
      ru: "Скала",
      nl: "Rots",
      de: "Fels",
      el: "Βράχος",
      ar: "صخرة",
      tags: "ground",
    },
    {
      emoji: "🍁",
      en: "Leaf",
      es: "Hoja",
      pt: "Folha",
      zh: "树叶",
      it: "Foglia",
      fr: "Feuille",
      ja: "葉っぱ",
      ko: "나뭇잎",
      ru: "Лист",
      nl: "Blad",
      de: "Blatt",
      el: "Φύλλο",
      ar: "ورقة",
      tags: "tree fall",
    },
    {
      emoji: "🌙",
      en: "Moon",
      es: "Luna",
      pt: "Lua",
      zh: "月亮",
      it: "Luna",
      fr: "Lune",
      ja: "月",
      ko: "달",
      ru: "Луна",
      nl: "Maan",
      de: "Mond",
      el: "Φεγγάρι",
      ar: "قمر",
      tags: "night sky space",
    },
    {
      emoji: "⭐",
      en: "Star",
      es: "Estrella",
      pt: "Estrela",
      zh: "星星",
      it: "Stella",
      fr: "Étoile",
      ja: "星",
      ko: "별",
      ru: "Звезда",
      nl: "Ster",
      de: "Stern",
      el: "Αστέρι",
      ar: "نجمة",
      tags: "night sky space",
    },
    {
      emoji: "🌊",
      en: "Wave",
      es: "Ola",
      pt: "Onda",
      zh: "海浪",
      it: "Onda",
      fr: "Vague",
      ja: "波",
      ko: "파도",
      ru: "Волна",
      nl: "Golf",
      de: "Welle",
      el: "Κύμα",
      ar: "موجة",
      tags: "sea water",
    },
  ],
  faces: [
    {
      emoji: "🚀",
      en: "Rocket",
      es: "Cohete",
      pt: "Foguete",
      zh: "火箭",
      it: "Razzo",
      fr: "Fusée",
      ja: "ロケット",
      ko: "로켓",
      ru: "Ракета",
      nl: "Raket",
      de: "Rakete",
      el: "Πυραυλος",
      ar: "صاروخ",
      tags: "space avatar",
    },
    {
      emoji: "👽",
      en: "Alien",
      es: "Extraterrestre",
      pt: "Aliens",
      zh: "外星人",
      it: "Alieno",
      fr: "Extraterrestre",
      ja: "エイリアン",
      ko: "외계인",
      ru: "Пришелец",
      nl: "Buitenaards wezen",
      de: "Außerirdischer",
      el: "Εξωγήινος",
      ar: "فضائي",
      tags: "space avatar",
    },
    {
      emoji: "🪐",
      en: "Planet",
      es: "Planeta",
      pt: "Planeta",
      zh: "行星",
      it: "Pianeta",
      fr: "Planète",
      ja: "惑星",
      ko: "행성",
      ru: "Планета",
      nl: "Planeet",
      de: "Planet",
      el: "Πλανήτης",
      ar: "كوكب",
      tags: "space avatar",
    },
    {
      emoji: "🦸",
      en: "Hero",
      es: "Héroe",
      pt: "Herói",
      zh: "英雄",
      it: "Eroe",
      fr: "Héros",
      ja: "ヒーロー",
      ko: "영웅",
      ru: "Герой",
      nl: "Held",
      de: "Held",
      el: "Ήρωας",
      ar: "بطل",
      tags: "superhero avatar",
    },
    {
      emoji: "🧚",
      en: "Fairy",
      es: "Hada",
      pt: "Fada",
      zh: "仙子",
      it: "Fata",
      fr: "Fée",
      ja: "妖精",
      ko: "요정",
      ru: "Фея",
      nl: "Fee",
      de: "Fee",
      el: "Νεράιδα",
      ar: "جنية",
      tags: "magic avatar",
    },
    {
      emoji: "🤖",
      en: "Robot",
      es: "Robot",
      pt: "Robô",
      zh: "机器人",
      it: "Robot",
      fr: "Robot",
      ja: "ロボット",
      ko: "로봇",
      ru: "Робот",
      nl: "Robot",
      de: "Roboter",
      el: "Ρομπότ",
      ar: "روبوت",
      tags: "space avatar",
    },
    {
      emoji: "🐻",
      en: "Bear",
      es: "Oso",
      pt: "Urso",
      zh: "熊",
      it: "Orso",
      fr: "Ours",
      ja: "クマ",
      ko: "곰",
      ru: "Медведь",
      nl: "Beer",
      de: "Bär",
      el: "Αρκούδα",
      ar: "دب",
      tags: "forest avatar",
    },
    {
      emoji: "🦊",
      en: "Fox",
      es: "Zorro",
      pt: "Raposa",
      zh: "狐狸",
      it: "Volpe",
      fr: "Renard",
      ja: "キツネ",
      ko: "여우",
      ru: "Лиса",
      nl: "Vos",
      de: "Fuchs",
      el: "Αλεπού",
      ar: "ثعلب",
      tags: "forest avatar",
    },
    {
      emoji: "🦄",
      en: "Unicorn",
      es: "Unicornio",
      pt: "Unicórnio",
      zh: "独角兽",
      it: "Unicorno",
      fr: "Licorne",
      ja: "ユニコーン",
      ko: "유니콘",
      ru: "Единорог",
      nl: "Eenhoorn",
      de: "Einhorn",
      el: "Μονόκερος",
      ar: "وحيد القرن",
      tags: "magic avatar",
    },
    {
      emoji: "🐙",
      en: "Octopus",
      es: "Pulpo",
      pt: "Polvo",
      zh: "章鱼",
      it: "Polpo",
      fr: "Pieuvre",
      ja: "タコ",
      ko: "문어",
      ru: "Осьминог",
      nl: "Inktvis",
      de: "Oktopus",
      el: "Χταπόδι",
      ar: "أخطبوط",
      tags: "sea avatar",
    },
  ],
};

export const PICTURES: Pic[] = Object.entries(RAW_ROWS).flatMap(([group, rows]) =>
  rows.map((r, i) => ({
    id: `${group}-${i}`,
    emoji: r.emoji,
    labels: {
      en: r.en,
      es: r.es,
      pt: r.pt,
      zh: r.zh,
      it: r.it,
      fr: r.fr,
      ja: r.ja,
      ko: r.ko,
      ru: r.ru,
      nl: r.nl,
      de: r.de,
      el: r.el,
      ar: r.ar,
    },
    tags: [group, ...r.tags.split(" ")],
  })),
);

export function searchPictures(query: string, limit = 60): Pic[] {
  const q = query.trim().toLowerCase();
  if (!q) return PICTURES.slice(0, limit);
  return PICTURES.filter(
    (p) =>
      p.tags.some((t) => t.includes(q)) ||
      Object.values(p.labels).some((l) => l.toLowerCase().includes(q)) ||
      p.emoji === q,
  ).slice(0, limit);
}

export const AVATAR_FACES = PICTURES.filter((p) => p.tags.includes("avatar"));
